[build]
command = "npm run build"
publish = "build"

[[headers]]
for = "/*.js"
[headers.values]
Content-Type = "text/javascript"
Access-Control-Allow-Origin = "*"

[[headers]]
for = "/*.mjs"
[headers.values]
Content-Type = "text/javascript"
Access-Control-Allow-Origin = "*"

# Optional: Add CORS headers if needed
[[headers]]
  for = "/*.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
 
[[headers]]
  for = "/*.mjs"
  [headers.values]
    Access-Control-Allow-Origin = "*"
 
# Optional: Configure redirects if needed
[[redirects]]
   from = "/*"
   to = "/index.html"
   status = 200
