[build]
command = "npm run build"
publish = "build"

[[headers]]
for = "/*.js"
[headers.values]
Content-Type = "text/javascript"
Access-Control-Allow-Origin = "*"

[[headers]]
for = "/*.mjs"
[headers.values]
Content-Type = "text/javascript"
Access-Control-Allow-Origin = "*"


